stages:
  - build

build-job:
  tags:
    - blue2
  stage: build
  script:
    - echo cool
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$WEBSITE_KEY")
    - ls
    - ./gradlew build
    - ./gradlew javdoc
    - ls
    
    
    
    - rsync -auvz -e "ssh" build/reports/tests/ raphaelsandor@atria.cs.odu.edu
    - rsync -auvz -e "ssh" build/docs/ rsandor@atria.cs.odu.edu
    - ssh-agent -k
  only:
    - master
