stages:
  - build

build-job:
  tags:
    - blue2
  stage: build
  script:
    - echo cool
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$WEBSITE_KEY")
    - cd src/main/resources/
    - chmod +x deploy.sh
    - ./deploy.sh
  only:
    - master
