stages:
  - build

build-job:
  tags:
    - blue2
  stage: build
  script:
    - echo build number is $CI_BUILD_REF
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$WEBSITE_KEY")
    - ls
    - ./gradlew build
    - ./gradlew javadoc
    - ./gradlew reports
    
    
    
    - rsync -auvz -e "ssh" build/reports/tests/ raphaelsandor@atria.cs.odu.edu:home/rsandor/public_html/cs350/build/reports/tests/test/index.html
    - rsync -auvz -e "ssh" build/docs/ rsandor@atria.cs.odu.edu:home/rsandor/public_html/cs350/build/docs/
    - ssh-agent -k
  only:
    - master
