stages:
  - build

build-job:
  tags:
    - blue2
  stage: build
  script:
    - echo cool
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$WEBSITE_KEY")

    - rsync -auvz -e "ssh" build/reports/tests/ raphaelsandor@atria.cs.odu.edu:./

  only:
    - master
