stages:
  - build

build-job:
  tags:
    - blue2
  stage: build
  script:
    - echo build number is $CI_BUILD_REF
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$WEBSITE_KEY")
    - ls
    - ./gradlew build
    - ./gradlew javadoc
    - ./gradlew reports
    
    
    
    - rsync -auvz -e "ssh" build/reports/ raphaelsandor@atria.cs.odu.edu
    - ssh-agent -k
  only:
    - master
